@startuml
skinparam titleBackgroundColor Aqua-CadetBlue
title Icap对ssh协议处理的时序图
SshClient -[#0000FF]-> Sslproxy: 收到来自客户端的数据
Sslproxy -> IcapServer: 封装数据为ICAP协议，发送给ICAP服务端
IcapServer -> Sslproxy: 回复200
Sslproxy --[#0000FF]> SshClient: 关闭该Channel
@enduml