
@startmindmap
skinparam titleBackgroundColor Aqua-CadetBlue
title SSH的消息类型;红色为icap关心类型,蓝色为透传类型,灰色为ssh协议内部处理类型
+[#Orange] SSH协议消息类型
++ SSH信息
+++[#lightblue] SSH2_MSG_DISCONNECT 1\nSSH2_MSG_IGNORE 2\nSSH2_MSG_UNIMPLEMENTED 3
+++[#lightblue] SSH2_MSG_DEBUG 4\nSSH2_MSG_SERVICE_REQUEST 5\nSSH2_MSG_SERVICE_ACCEPT 6
+++[#lightblue] SSH2_MSG_EXT_INFO 7
++ 加密协商过程
+++ SSH2_MSG_KEXINIT 20\nSSH2_MSG_NEWKEYS 21
+++ SSH2_MSG_KEXDH_INIT 30\nSSH2_MSG_KEX_DH_GEX_REQUEST_OLD 30
+++ SSH2_MSG_KEXDH_REPLY 31\nSSH2_MSG_KEX_DH_GEX_GROUP 31
+++ SSH2_MSG_KEX_DH_GEX_INIT 32\nSSH2_MSG_KEX_DH_GEX_REPLY 33\nSSH2_MSG_KEX_DH_GEX_REQUEST 34
-- 用户认证信息
---[#lightblue] SSH2_MSG_USERAUTH_REQUEST 50\nSSH2_MSG_USERAUTH_FAILURE 51\nSSH2_MSG_USERAUTH_SUCCESS 52\nSSH2_MSG_USERAUTH_BANNER 53
---[#lightblue] SSH2_MSG_USERAUTH_PK_OK 60\nSSH2_MSG_USERAUTH_PASSWD_CHANGEREQ 60\nSSH2_MSG_USERAUTH_INFO_REQUEST 60\nSSH2_MSG_USERAUTH_GSSAPI_RESPONSE 60
---[#lightblue] SSH2_MSG_USERAUTH_INFO_RESPONSE 61\nSSH2_MSG_USERAUTH_GSSAPI_TOKEN 61
--- SSH2_MSG_USERAUTH_GSSAPI_EXCHANGE_COMPLETE 63\nSSH2_MSG_USERAUTH_GSSAPI_ERROR 64\nSSH2_MSG_USERAUTH_GSSAPI_ERRTOK 65\nSSH2_MSG_USERAUTH_GSSAPI_MIC 66
++ 服务请求
+++[#lightblue] SSH2_MSG_GLOBAL_REQUEST 80\nSSH2_MSG_REQUEST_SUCCESS 81\nSSH2_MSG_REQUEST_FAILURE 82
-- 隧道信息
---[#lightblue] SSH2_MSG_CHANNEL_OPEN 90
---[#FFBBCC] SSH2_MSG_CHANNEL_OPEN_CONFIRMATION  91\nSSH2_MSG_CHANNEL_OPEN_FAILURE 92
---[#lightblue] SSH2_MSG_CHANNEL_WINDOW_ADJUST 93
---[#FFBBCC] SSH2_MSG_CHANNEL_DATA 94
---[#lightblue] SSH2_MSG_CHANNEL_EXTENDED_DATA 95
---[#FFBBCC] SSH2_MSG_CHANNEL_EOF 96\nSSH2_MSG_CHANNEL_CLOSE 97
---[#FFBBCC] SSH2_MSG_CHANNEL_REQUEST 98\nSSH2_MSG_CHANNEL_SUCCESS 99
---[#lightblue] SSH2_MSG_CHANNEL_FAILURE 100
@endmindmap