@startmindmap

*[#Orange] 网络学习 
**[#lightgreen] 1. 交换技术介绍
***_ 1.1 交换网络基础
***_ 1.2 VLAN学习
***_ 1.3 FDB了解

**[#lightgreen] 2. 路由技术介绍
***_ 2.1 路由网络基础
***_ 2.2 IP报文学习
***_ 2.3 静态路由学习
***_ 2.4 动态路由学习

**[#lightgreen] 3. 传输层技术介绍
***_ 3.1 TCP报文学习
***_ 3.2 TCP状态机了解

--[#lightblue] 学习目的
---_ 运维工作
---_ 测试工作
---_ 丰富网络知识

--[#lightblue] 学习对象
---_ 在校学生
---_ 已经工作想转IT的同学

@endmindmap